server:
  address: ":8080"
  tls:
    enabled: true
    ca_cert: "certs/ca/ca.crt"
    server_cert: "certs/server/server.crt"
    server_key: "certs/server/server.key"

kafka:
  brokers:
    - "localhost:9092"
  consumer_group: "kafka-gateway"
  security_protocol: "PLAINTEXT"  # Options: PLAINTEXT, SASL_PLAINTEXT, SASL_SSL, SSL

auth:
  enabled: false
  secret: ""  # This will be your API key for authorization

storage:
  sqlite:
    enabled: true
    db_path: "./data/messages.db"
    table_name: "kafka_messages"